/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5XiKADd3klU
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Crimson_Text } from 'next/font/google'
import { DM_Serif_Display } from 'next/font/google'

crimson_text({
  subsets: ['latin'],
  display: 'swap',
})

dm_serif_display({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Screen() {
  return (
    <div
      className="relative w-full min-h-[100dvh] bg-cover bg-center bg-no-repeat"
      style={{ backgroundImage: `url('/image_djerba.webp')` }}
    >
      <div className="absolute inset-0 bg-black/50"/>
      <div className="relative  text-center text-white">
        <div className="space-y-10 md:space-y-50 lg:space-y-100">
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3 animate-slide-up delay-200">
            <div className="bg-white/10 rounded-lg p-3 text-left">
              <h3 className="text-lg font-semibold">5 Juillet</h3> <a href="https://maps.app.goo.gl/Af5nvmefyWtJtHR26"><img src="/houch.png"/></a>
              <p className="text-sm text-gray-300">19:30 PM - 22:00 PM  <b>Dîner</b></p>
              <p className="text-sm text-gray-300">23:00 PM - 2:00 AM <b>Zahow Jerbi (Fête Djerbienne)</b></p>
	    </div>
	    <div className="bg-white/10 rounded-lg p-3 text-left"> 	
              <p className="text-sm text-gray-200">18:30 PM - 20:00 PM <b>Barboura</b></p>
              <p className="text-sm text-gray-200">21:30 PM - 2:00 AM <b>Chwachen (Fête pour les femmes)</b></p>
	      <h3 className="text-lg font-semibold">6 Juillet</h3> <a href="https://maps.app.goo.gl/Af5nvmefyWtJtHR26"><img src="/houch.png"/></a>	
	   </div>
	   <div className="bg-white/10 rounded-lg p-3 text-left"> 
              <h3 className="text-lg font-semibold">7 Juillet</h3> <a href="https://maps.app.goo.gl/CmRynA7upbRFEwHf8"><img src="/houch.png"/></a>
              <p className="text-sm text-gray-200">20:00 PM - 00:00 AM <b>Jahfa (Soirée finale )</b></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
